using System;

using Microsoft.CodeAnalysis;

namespace FastEnumToString
{
    /// <summary>
    /// Generates a <em>FastToString</em> method for each enum in the referencing assembly.<br />
    /// From <see cref="ISourceGenerator"/>:<br />
    /// <inheritdoc/>
    /// </summary>
    [Generator(LanguageNames.CSharp)]
    public class EnumToStringGenerator : ISourceGenerator
    {
        private const string GeneratedFileName = "EnumStringConverter.g.cs";
        private const string ExcludeAttributeFile = "ExcludeToStringAttribute.g.cs";
        private const string ExcludeAttribute = @"// <auto-generated />

namespace FastEnumToString
{
    [global::System.AttributeUsage(global::System.AttributeTargets.Enum)]
    public class ExcludeToStringAttribute : global::System.Attribute { }
}
";
        
        /// <inheritdoc/>
        public void Initialize(GeneratorInitializationContext context)
        {
#if DEBUG
            if (!System.Diagnostics.Debugger.IsAttached)
            {
                System.Diagnostics.Debugger.Launch();
            }
#endif

            context.RegisterForPostInitialization(ctx =>
                ctx.AddSource(ExcludeAttributeFile, ExcludeAttribute));
            context.RegisterForSyntaxNotifications(() => new EnumToStringSyntaxReciever());
        }

        /// <inheritdoc/>
        public void Execute(GeneratorExecutionContext context)
        {
            if (!(context.SyntaxReceiver is EnumToStringSyntaxReciever reciever))
            {
                return;
            }

            if (reciever.Enums.Count == 0)
            {
                context.AddSource(GeneratedFileName, EnumProcessor.Empty);
                return;
            }

            context
                .AnalyzerConfigOptions.GlobalOptions
                .TryGetValue("build_property.FastEnumFallbackValue", out string fallback);
            context
                .AnalyzerConfigOptions.GlobalOptions
                .TryGetValue("build_property.rootnamespace", out string rootNameSpace);

            FallbackType fallbackType = ParseFallbackValue(fallback);

            EnumProcessor processor = new EnumProcessor(context, rootNameSpace)
            {
                Fallback = fallbackType
            };

            string generatedClass = processor.Process(reciever.Enums);

            context.AddSource(GeneratedFileName, generatedClass);
        }

        private static FallbackType ParseFallbackValue(string fallback)
        {
            if (String.IsNullOrWhiteSpace(fallback))
            {
                return FallbackType.Throw;
            }

            fallback = fallback.Trim().ToLower();
            switch (fallback)
            {
                case "default":
                    return FallbackType.Default;
                case "first":
                    return FallbackType.First;
                default:
                    return FallbackType.Throw;
            }
        }
    }
}

